### ISSUE TITLE
functions azimuth/elevation/roll while using K3D window

### ISSUE THREAD

**Issue by ahinoamp** [marcomusy/vtkplotter-examples#3]
Hi Marco,

I have one more new question, since it's different, I put it in a new issue.

I am having trouble manipulating the camera in Jupyter Notebook mode using `embedWindow('k3d')`

**The functions azimuth/elevation/roll do not seem to work for me.** 

I use them as follows:
`plot.show(viewup='z', azimuth=30)`
Also, I'm not sure whether their units are from 0-360 or perhaps 0-1. 

In general, I'm trying to manipulate the camera in various ways, but the only way I've succeeded so far is by using the following code:
```
settings.notebook_plotter.camera = [maxX/2, maxY/2+10000, maxZ/2,
                                    maxX/2, maxY/2, maxZ/2,
                                    0., 0., 1.] 
```
But I prefer not to use this method since it only works by running it in the cell below the plot cell.

Thank you again for your assistance. 

Noe

**Comment by marcomusy** [comment]
Hi Noe,
Unfortunately many functions related to the camera management - like the ones you mention - are unavailable in notebooks because of the way the k3d backend is controlling the scene..
The only suggestion I can give you is to refer to example in [here](https://github.com/marcomusy/vtkplotter-examples/blob/master/vtkplotter_examples/notebooks/manipulate_camera.ipynb) to see what is possible to do if you need to embed the graphic window in the notebook document.
Marco

**Comment by ahinoamp** [comment]
Thanks Marco for your quick response!
It's good to know that I'm not missing out on something. 
I might start to use the pop-out VTK window.
Again, thanks for all your work. This is the perfect package for visualizing my research. 

Noe
